import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { Route, Routes } from 'react-router-dom';
import { AuthProvider } from '../auth/AuthContext';
import { ProtectedRoute } from '../auth/ProtectedRoute';
import RoleRoute from '../auth/RoleRoute';
import Login from '../pages/Login';
import Register from '../pages/Register';
import Signup from '../pages/Signup';
import Forbidden from '../pages/Forbidden';
import Dashboard from '../pages/Dashboard';
import Projects from '../pages/Projects';
import ProjectView from '../pages/Projects/ProjectView';
import Documents from '../pages/Documents';
import DocumentsCompanyList from '../pages/DocumentsCompanyList';
import DocumentsLibrary from '../pages/DocumentsLibrary';
import Finance from '../pages/Finance';
import FinanceInvoices from '../pages/Finance/Invoices';
import HR from '../pages/HR';
import HRProjectWiseReport from '../pages/HR/ProjectWiseReport';
import Admin from '../pages/Admin';
import Analytics from '../pages/Analytics';
import Layout from '../components/Layout';
import DashboardKPIs from '../pages/Dashboard/KPIs';
import DashboardActivities from '../pages/Dashboard/RecentActivities';
import DashboardNotifications from '../pages/Dashboard/Notifications';
import FinanceExpenses from '../pages/Finance/Expenses';
import FinanceExpensePage from '../pages/Finance/Expense';
import FinanceGeneralExpensePage from '../pages/Finance/GeneralExpense';
import FinanceManpowerExpensePage from '../pages/Finance/ManpowerExpense';
import CompanyEmployeeSalaryExpensePage from '../pages/Finance/CompanyEmployeeSalaryExpense';
import ExternalLabourExpensePage from '../pages/Finance/ExternalLabourExpense';
import FinanceBudgets from '../pages/Finance/Budgets';
import FinanceProfitLoss from '../pages/Finance/ProfitLoss';
import FinanceReports from '../pages/Finance/Reports';
import FinanceInvoicesPreviewPage from '../pages/Finance/FinanceInvoicesPreview';
import FinanceExpenseInvoicePreviewPage from '../pages/Finance/FinanceExpenseInvoicePreview';
import FinanceGeneralExpensePreviewPage from '../pages/Finance/FinanceGeneralExpensePreview';
import FinanceCompanySalaryPreviewPage from '../pages/Finance/FinanceCompanySalaryPreview';
import FinanceExternalLabourPreviewPage from '../pages/Finance/FinanceExternalLabourPreview';
import HRAttendance from '../pages/HR/Attendance';
import HRAttendanceManpowerSupplier from '../pages/HR/ManpowerSupplier';
import HRAttendanceManpowerSupplierAddRecords from '../pages/HR/ManpowerSupplierAddRecords';
import HRAttendanceEntry from '../pages/HR/AttendanceEntry';
import HRAttendanceRecords from '../pages/HR/AttendanceRecords';
import HRAttendanceEmployeeMonthly from '../pages/HR/AttendanceEmployeeMonthly';
import HREmployees from '../pages/HR/Employees';
import HRPayroll from '../pages/HR/Payroll';
import HRPayrollDetails from '../pages/HR/PayrollDetails';
import { PermissionRoute } from '../auth/PermissionRoute';
import MaterialDelivery from '../pages/Projects/MaterialDelivery';
import AdminUsers from '../pages/Admin/Users';
import AdminRoles from '../pages/Admin/RolesPermissions';
import AdminLogs from '../pages/Admin/SystemLogs';
import AdminSettings from '../pages/Admin/AppSettings';
import AdminSync from '../pages/Admin/SyncStatus';
import AdminBackup from '../pages/Admin/Backup';
import AnalyticsFinancial from '../pages/Analytics/FinancialAnalytics';
import AnalyticsEmployee from '../pages/Analytics/EmployeeAnalytics';
import AnalyticsProject from '../pages/Analytics/ProjectPerformance';
import AnalyticsReports from '../pages/Analytics/BusinessReports';
import AnalyticsBuilder from '../pages/Analytics/ReportBuilder';
import UtilNotifications from '../pages/Utility/NotificationsCenter';
import UtilCalendar from '../pages/Utility/Calendar';
import UtilDocuments from '../pages/Utility/Documents';
import UtilHelp from '../pages/Utility/SupportHelp';
import UtilProfile from '../pages/Utility/ProfileSettings';
export default function App() {
    return (_jsx(AuthProvider, { children: _jsxs(Routes, { children: [_jsx(Route, { path: "/login", element: _jsx(Login, {}) }), _jsx(Route, { path: "/register", element: _jsx(Register, {}) }), _jsx(Route, { path: "/auth/login", element: _jsx(Login, {}) }), _jsx(Route, { path: "/auth/register", element: _jsx(Register, {}) }), _jsx(Route, { path: "/auth/signup", element: _jsx(Signup, {}) }), _jsx(Route, { path: "/signup", element: _jsx(Signup, {}) }), _jsx(Route, { path: "/403", element: _jsx(Forbidden, {}) }), _jsxs(Route, { element: _jsx(ProtectedRoute, {}), children: [_jsx(Route, { path: "/", element: _jsx(Layout, { children: _jsx(Dashboard, {}) }) }), _jsxs(Route, { element: _jsx(RoleRoute, { allow: ["ADMIN", "GM", "PROJECT_MANAGER", "ACCOUNTANT", "MANAGER", "Team Leader", "Office Desk", "Recorder"] }), children: [_jsx(Route, { path: "/projects", element: _jsx(Layout, { children: _jsx(Projects, {}) }) }), _jsx(Route, { path: "/projects/view/:id", element: _jsx(Layout, { children: _jsx(ProjectView, {}) }) }), _jsx(Route, { path: "/projects/:id/material-delivery", element: _jsx(Layout, { children: _jsx(MaterialDelivery, {}) }) })] }), _jsxs(Route, { element: _jsx(RoleRoute, { allow: ["ADMIN", "GM", "ACCOUNTANT", "MANAGER", "Team Leader", "Office Desk", "Recorder"] }), children: [_jsx(Route, { path: "/documents-main", element: _jsx(Layout, { children: _jsx(Documents, {}) }) }), _jsx(Route, { path: "/documents-main/company-list", element: _jsx(Layout, { children: _jsx(DocumentsCompanyList, {}) }) }), _jsx(Route, { path: "/documents-main/documents", element: _jsx(Layout, { children: _jsx(DocumentsLibrary, {}) }) })] }), _jsxs(Route, { element: _jsx(RoleRoute, { allow: ["ADMIN", "GM", "FINANCE_MANAGER", "ACCOUNTANT", "MANAGER", "Team Leader", "Office Desk", "Recorder"] }), children: [_jsx(Route, { path: "/finance", element: _jsx(Layout, { children: _jsx(Finance, {}) }) }), _jsx(Route, { path: "/finance/invoices", element: _jsx(Layout, { children: _jsx(FinanceInvoices, {}) }) }), _jsx(Route, { path: "/finance/expenses", element: _jsx(Layout, { children: _jsx(FinanceExpenses, {}) }) }), _jsx(Route, { path: "/finance/expenses/expense", element: _jsx(Layout, { children: _jsx(FinanceExpensePage, {}) }) }), _jsx(Route, { path: "/finance/expenses/general", element: _jsx(Layout, { children: _jsx(FinanceGeneralExpensePage, {}) }) }), _jsx(Route, { path: "/finance/expenses/manpower", element: _jsx(Layout, { children: _jsx(FinanceManpowerExpensePage, {}) }) }), _jsx(Route, { path: "/finance/expenses/company-employee-salary", element: _jsx(Layout, { children: _jsx(CompanyEmployeeSalaryExpensePage, {}) }) }), _jsx(Route, { path: "/finance/expenses/manpower/external-labour-expense", element: _jsx(Layout, { children: _jsx(ExternalLabourExpensePage, {}) }) }), _jsx(Route, { path: "/finance/budgets", element: _jsx(Layout, { children: _jsx(FinanceBudgets, {}) }) }), _jsx(Route, { path: "/finance/profit-loss", element: _jsx(Layout, { children: _jsx(FinanceProfitLoss, {}) }) }), _jsx(Route, { path: "/finance/reports", element: _jsx(Layout, { children: _jsx(FinanceReports, {}) }) }), _jsx(Route, { path: "/finance/preview/invoices", element: _jsx(Layout, { children: _jsx(FinanceInvoicesPreviewPage, {}) }) }), _jsx(Route, { path: "/finance/preview/expense-invoice", element: _jsx(Layout, { children: _jsx(FinanceExpenseInvoicePreviewPage, {}) }) }), _jsx(Route, { path: "/finance/preview/general-expense", element: _jsx(Layout, { children: _jsx(FinanceGeneralExpensePreviewPage, {}) }) }), _jsx(Route, { path: "/finance/preview/company-employee-salary", element: _jsx(Layout, { children: _jsx(FinanceCompanySalaryPreviewPage, {}) }) }), _jsx(Route, { path: "/finance/preview/external-labour-expense", element: _jsx(Layout, { children: _jsx(FinanceExternalLabourPreviewPage, {}) }) })] }), _jsxs(Route, { element: _jsx(RoleRoute, { allow: ["ADMIN", "GM", "HR_MANAGER", "ACCOUNTANT", "MANAGER", "Team Leader", "Office Desk", "Recorder"] }), children: [_jsx(Route, { path: "/hr", element: (_jsx(Layout, { children: _jsx(PermissionRoute, { permission: "HR.View", children: _jsx(HR, {}) }) })) }), _jsx(Route, { path: "/hr/attendance", element: (_jsx(Layout, { children: _jsx(PermissionRoute, { permission: "HR.Attendance.View", children: _jsx(HRAttendance, {}) }) })) }), _jsx(Route, { path: "/hr/attendance/entry", element: (_jsx(Layout, { children: _jsx(PermissionRoute, { permission: "HR.Attendance.Entry.View", children: _jsx(HRAttendanceEntry, {}) }) })) }), _jsx(Route, { path: "/hr/attendance/records", element: (_jsx(Layout, { children: _jsx(PermissionRoute, { permission: "HR.Attendance.Records.View", children: _jsx(HRAttendanceRecords, {}) }) })) }), _jsx(Route, { path: "/hr/attendance/manpower-supplier", element: (_jsx(Layout, { children: _jsx(PermissionRoute, { permission: "HR.Attendance.ManpowerSupplier.View", children: _jsx(HRAttendanceManpowerSupplier, {}) }) })) }), _jsx(Route, { path: "/hr/attendance/manpower-supplier/add-records", element: (_jsx(Layout, { children: _jsx(PermissionRoute, { permission: "HR.Attendance.ManpowerSupplier.View", children: _jsx(HRAttendanceManpowerSupplierAddRecords, {}) }) })) }), _jsx(Route, { path: "/hr/attendance/employee/:employeeId", element: (_jsx(Layout, { children: _jsx(PermissionRoute, { permission: "HR.Attendance.Records.View", children: _jsx(HRAttendanceEmployeeMonthly, {}) }) })) }), _jsx(Route, { path: "/hr/employees", element: (_jsx(Layout, { children: _jsx(PermissionRoute, { permission: "HR.Employees.View", children: _jsx(HREmployees, {}) }) })) }), _jsx(Route, { path: "/hr/payroll", element: (_jsx(Layout, { children: _jsx(PermissionRoute, { permission: "HR.Payroll.View", children: _jsx(HRPayroll, {}) }) })) }), _jsx(Route, { path: "/hr/payroll/:employeeId/:emiratesId", element: (_jsx(Layout, { children: _jsx(PermissionRoute, { permission: "HR.Payroll.Details.View", children: _jsx(HRPayrollDetails, {}) }) })) }), _jsx(Route, { path: "/hr/project-wise-report", element: (_jsx(Layout, { children: _jsx(PermissionRoute, { permission: "HR.View", children: _jsx(HRProjectWiseReport, {}) }) })) })] }), _jsx(Route, { element: _jsx(RoleRoute, { allow: ["ADMIN", "GM", "SUPERADMIN", "Office Desk"] }), children: _jsx(Route, { path: "/admin", element: _jsx(Layout, { children: _jsx(Admin, {}) }) }) }), _jsxs(Route, { element: _jsx(RoleRoute, { allow: ["ADMIN", "SUPERADMIN"] }), children: [_jsx(Route, { path: "/admin/users", element: _jsx(Layout, { children: _jsx(AdminUsers, {}) }) }), _jsx(Route, { path: "/admin/roles", element: _jsx(Layout, { children: _jsx(AdminRoles, {}) }) }), _jsx(Route, { path: "/admin/logs", element: _jsx(Layout, { children: _jsx(AdminLogs, {}) }) }), _jsx(Route, { path: "/admin/settings", element: _jsx(Layout, { children: _jsx(AdminSettings, {}) }) }), _jsx(Route, { path: "/admin/sync", element: _jsx(Layout, { children: _jsx(AdminSync, {}) }) }), _jsx(Route, { path: "/admin/backup", element: _jsx(Layout, { children: _jsx(AdminBackup, {}) }) })] }), _jsxs(Route, { element: _jsx(RoleRoute, { allow: ["ADMIN", "GM", "SUPERADMIN", "Team Leader", "Office Desk"] }), children: [_jsx(Route, { path: "/analytics", element: _jsx(Layout, { children: _jsx(Analytics, {}) }) }), _jsx(Route, { path: "/analytics/overview", element: _jsx(Layout, { children: _jsx(Analytics, {}) }) }), _jsx(Route, { path: "/analytics/financial", element: _jsx(Layout, { children: _jsx(AnalyticsFinancial, {}) }) }), _jsx(Route, { path: "/analytics/employee", element: _jsx(Layout, { children: _jsx(AnalyticsEmployee, {}) }) }), _jsx(Route, { path: "/analytics/projects", element: _jsx(Layout, { children: _jsx(AnalyticsProject, {}) }) }), _jsx(Route, { path: "/analytics/reports", element: _jsx(Layout, { children: _jsx(AnalyticsReports, {}) }) }), _jsx(Route, { path: "/analytics/builder", element: _jsx(Layout, { children: _jsx(AnalyticsBuilder, {}) }) }), _jsx(Route, { path: "/analytics/custom", element: _jsx(Layout, { children: _jsx(AnalyticsBuilder, {}) }) })] }), _jsx(Route, { path: "/dashboard/kpis", element: _jsx(Layout, { children: _jsx(DashboardKPIs, {}) }) }), _jsx(Route, { path: "/dashboard/activities", element: _jsx(Layout, { children: _jsx(DashboardActivities, {}) }) }), _jsx(Route, { path: "/dashboard/notifications", element: _jsx(Layout, { children: _jsx(DashboardNotifications, {}) }) }), _jsx(Route, { path: "/notifications", element: _jsx(Layout, { children: _jsx(UtilNotifications, {}) }) }), _jsx(Route, { path: "/calendar", element: _jsx(Layout, { children: _jsx(UtilCalendar, {}) }) }), _jsx(Route, { path: "/documents", element: _jsx(Layout, { children: _jsx(UtilDocuments, {}) }) }), _jsx(Route, { path: "/help", element: _jsx(Layout, { children: _jsx(UtilHelp, {}) }) }), _jsx(Route, { path: "/profile", element: _jsx(Layout, { children: _jsx(UtilProfile, {}) }) })] })] }) }));
}
